### ISSUE TITLE
getting messages but can't see a thing on opencpn

### ISSUE THREAD

**Issue by j2l** [jvde-github/AIS-catcher-for-Android#3]
Hi, 
Your project seems great!
I have a RTL-SDR receiver and live near the sea, I successfully got 11 messages (type: other) and set up a connection (UDP, 127.0.0.1:10110) on opencpn free (android) but I don't see any boat on the map.

Would you please share the full process to link your catcher and opencpn?

Thank you

**Comment by jvde-github** [comment]
Hi, I will add something to the github page early next week. You should be able to easily set this up in the settings menu.
You mention that you received messages of type "other". It might be that OpenCPN receives and processes these but does not result in ships on the map (typically comes from msg 1-3 and 5). You can confirm that OpenCPN receives messages from AIS-catcher by selecting the Debug NMEA window in the Connections menu. This then adds a window that should show the same messages as send by AIS-catcher.

Nevertheless, I will add a step-by-step guide next week for OpenCPN and BoatBeacon.

Thanks for your interest,
Jasper

**Comment by j2l** [comment]
Thank you very much @jvde-github!
Can't wait to read your guide.

I'll check in OpenCPN ASAP and let you know.

**Comment by j2l** [comment]
OK, I see messages in openCPN, but I get nothing but `other` messages. Weird.
Receiving ADS-B works with the same setup (1090Mhz).

Maybe it's my antenna, which frequency is your AIS?
161.975Mhz and 162.025Mhz?

**Comment by jvde-github** [comment]
I think your connection with OpenCPN is set up properly then.

While ADS-B works nearly everywhere, AIS is a bit different. Ships are on sea level (and not at high altitude) and for this reason AIS travels much shorter distances (think 20 - 100km without major obstacles). So, this might be the cause?

You could use a site like marinetraffic.com or vesselfinder.com to check if there are vessels close to you that you should be receiving. Alternative is to test the mobile set up in an area like a port with some commercial vessels.

Kind regards, Jasper

**Comment by j2l** [comment]
Thank you @jvde-github, 

I tested it at the airplane club, near the sea (the final approach is on the sea). 

There are no big commercial ships here, but there are at least 5 ships in the nearby port visible on marinetraffic.
Most important, I noticed that my antenna is subpar when I compare it with the handheld receiver from the club when listening to the airport control tower.

162Mhz means a 1.85 m antenna. I need to find a way to get or build a good antenna I guess.
If you have tips, I'm all ears :smile: 

By any chance did you also try receiving marine weather?
I asked on hackrf but it's stuck for now: https://github.com/greatscottgadgets/hackrf/issues/1088#issuecomment-1165747872

Maybe there's another way to get weather information without (expensive) satellite fees.

**Comment by j2l** [comment]
Thank you @jvde-github 

I though of StarLink, but it's not working while moving and will get expensive sooner or later.

I tried something weird but it's working with FLdigi: 
- open fldigi (I'm on Linux, it also works on Windows)
- set FLdigi to record your playing audio
- play this youtube video:  https://www.youtube.com/watch?v=VGQK10svOzg
- you get a weather fax from 2012!

It's fun, but I'd like to get weather forecast (fax or else) while on sea (my receiver and antenna are from RTL-SDR.com, NOELEC is the same I think, but not the antenna).
Do you know where I could get a good but inexpensive antenna?

**Comment by j2l** [comment]
It (almost fully) works now, closing this one
