### ISSUE TITLE
Could you please update the apk on Google Drive？

### ISSUE THREAD

**Issue by mhrlb** [jvde-github/AIS-catcher-for-Android#5]
When the source codes have a major update, could you please update the apk on Google Drive？Thank you.😄

**Comment by jvde-github** [comment]
I just did! Let me know if it works. You might have to delete the previous version first. 

I removed the time limit of 2 minutes, added a wakelock and spyserver support.

**Comment by jvde-github** [comment]
Ok, I have set up the workflow such that after each commit automatically the latest APK file is build and signed and can be found under the Actions  menu. 

Unfortunately, you cannot link to these files so might have to download them first and write to your phone. That is why I still provide a download link on Google Drive.

Hopefully this helps.

**Comment by mhrlb** [comment]
thank you very much. I just downloaded the apk (V0.14) from activity/release!

**Comment by jvde-github** [comment]
great! I will close this item and going forward the latest build should always be available. Thanks for flagging.
