### ISSUE TITLE
AIS-catcher-for-Android stops receiving

### ISSUE THREAD

**Issue by syspart** [jvde-github/AIS-catcher-for-Android#6]
I have a no name rtl dongle.
When I start I get 20 to 60 Messages, and than it stops.
Even when I start the app again, or reattach the dongle, I only 0 to 2 new messages.
With the same setting, dongle and antenna, with windows 10 and SDRangel I get a continous stream of NMEA messages 
Any idea what is wrong?

**Comment by jvde-github** [comment]
Hi! Thanks. I have not seen this before personally. Any information on the phone and Android version? In what state is the program if it stops (background)?  And if it restarts do you see the "data received" counter still running?

The only thing I can think of is some battery optimization on the phone that does not grant the app the necessary running time after a while. I would play around a bit with the battery optimization settings for the app and see if that fixes it. 

You could also try another RTL-SDR app and see if it shows the same problem? Then we can conclude it is the App and not the phone. For example, run https://play.google.com/store/apps/details?id=marto.rtl_tcp_andro to which you could link AIS-catcher via the RTL-TCP driver.

**Comment by syspart** [comment]
The first device is a pixel 6 and android 13.
Now I tested it with samsung galaxy s5 and lineageos android version 11.
On lineage it starts with 25 messages. 
Than I deleted AIS-catcher restart the s5 installed ais-catcher reattach the dongle. And now I get 8 messages. Now I put the dongel in a freezer :-).
And after 10 min back, I receive new messages.
So its a temperature problem with the device.
But as stated before, with SDRangel there is no problem with the temperature, the dongle is little warm, and it gets the messages.

**Comment by syspart** [comment]
So with the cooled device I get 240 messages.
Data received counter is going on, but no more message are comming.

**Comment by jvde-github** [comment]
That freezer angle is funny. Thanks. So it is possible then that the heating of the device is causing some frequency drift that stops the app from properly receiving messages.  If data is still coming in but nothing being picked up, that could be an explanation.

Does not explain why it is running so hot on Android. In principle SDRangel and AIS-catcher are both using libusb and the rtlsdr library. The logic should not be too different.

I did a run for >6 hours running the App reporting to MarineTraffic without the issues you seem to experience. Either Android implementation needs to be tweaked (I will do some testing as well with dongles comparing Windows and Android), or Android does not like this particular dongle for whatever reason or could it have to do with an OTG cable somehow?

**Comment by syspart** [comment]
On both systems the dongle dont get hot. Maybe hand warm.

**Comment by jvde-github** [comment]
Yes, sorry, you did not say that, only that it seems to be temperature related. Will see if I can replicate with a blue dongle but I would try if swapping the OTG cable resolves the issue.

**Comment by jvde-github** [comment]
Ok, clear. If that is the case you would see a similar issue if you use AIS-catcher for Windows (https://github.com/jvde-github/AIS-catcher) which then should receive less messages than SDRangel on Windows. And then I think we can fix it (either by using a second algorithm embedded in AIS-catcher or introducing an extra setting making the App more forgiving on frequency drifts).

**Comment by jvde-github** [comment]
I think AIS-catcher allows +/- 4 ppm deviation in frequency before it starts to struggle which makes sense if there is no thermal drift as it gives a little bit of slack for the receiver and the sender. 

The other way to test this hypothesis of thermal drift is to, once no more messages are detected but data is still streaming, stop the detection, go to settings and find a PPM settings that possibly works and start again (settings only become effective when reception is started).

**Comment by syspart** [comment]
There is a shift to ~ -10ppm. Sometimes -16ppm. It depends on how long it is running, or if I heat it up with my hand.
But it was tricky, first I had to know, it could go downwards, and then testing it step by step.
And after of lot of start and stops, the buttons at the bottom ditn't react any longer (Stop, clear, rtlsdr). But I could open the hamburger menu and go into settings. I had to clear app data and cache. Couldn't reproduce it, but it happened 2x.

**Comment by jvde-github** [comment]
Ok, great, thanks for testing! Then it is definitely thermal shift of this particular dongle then. I have added two new settings to the App and will upload soon. Hopefully this gives some extra settings to overcome this issue.

**Comment by jvde-github** [comment]
Hello. I have created a new release with some extra options (https://github.com/jvde-github/AIS-catcher-for-Android/releases/tag/v0.21). 

If you go to Settings there is now a Receiver section at the bottom with a settings "Applied Frequency Correction". One thing you could try is to change this settings from Default -> Wide.

A second option is to change the Receiver setting Receiver Decoding Model from Default to FM decoding. This model is in general less sensitive to frequency drift but less sensitive. 

For other dongles which do not have this issue I would not advice to use these settings. 

Hope this works for you. I will upload to Play Store as well but this requires vetting from Google so will take some time before visible.

**Comment by syspart** [comment]
With applied frequency correction it is all fine.
I get 450 messages with 120 MB.
Thanks

**Comment by jvde-github** [comment]
Amazing, thanks for persevering to get to the bottom of this.

**Comment by syspart** [comment]
By the way, where do I get a openCPN map for the northsea.
Download from https://alpha.openseamap.org/ did not work for me. 
And the kap map I found on wiki.openseamap.org have terrible scale.

**Comment by jvde-github** [comment]
Don't know sorry,
