### ISSUE TITLE
Wrong version number?

### ISSUE THREAD

**Issue by syspart** [jvde-github/AIS-catcher-for-Android#7]
Moin, 
I installed your latest version, but it say's 0.21, and not 0.22.
Wrong apk or wrong number?
Greetings

**Comment by jvde-github** [comment]
Hi, I just updated the App in the play store and on github to version 23.  I noticed that if the receiver does not start (e.g. RTL-TCP as source without being able to make a connection) it does not close the UDP connections. This then results in an error if the receiver is started again. 

I checked the version in the play store and in the release section here and it both shows 0.38-23 as a first line in the LOG section. Hopefully that works for you as well?

**Comment by jvde-github** [comment]
One more thought, the app with version code 22 had a version name of '0.21' which is a discrepancy. I don't believe that is an issue but perhaps this is the version description you are referring to. In 23 the version name is again brought back in line '0.23'.

This might explain it.

Thanks, Jasper

**Comment by syspart** [comment]
Thanks this helped.
